# Fidelity properties for the MessageHandler
ACCOUNT_PREFIX=Fidelity-
DATE_FORMAT=MMM dd, yyyy
TRADE_REGEX=^\\s+Order (Partially Filled|Execution)\\s+Account\\s+(?<account>[X*]{5}\\d{4})\\s+(Your order to|Unit Investment Trust)\\s+(?<action>SELL|BUY)\\s*\\d*\\.\\d* (shares|units) of \\*?(?<symbol>[A-Z\\-]+) was \\*?(PARTIALLY )?FILLED\\s+\\*?FILLED\\s+(?<quantity>\\d*.\\d*) (shares|units)\\s+@ \\$(?<price>[\\d,]*.\\d*)$
FROM=fidelity.alerts@fidelity.com
SUBJECT_1=Fidelity Alerts: Order Execution
SUBJECT_2=Fidelity Alerts: Order Partially Filled