# properties for the Schwab Message handler
ACCOUNT_PREFIX=Schwab-XXXX
ACCOUNT_REGEX=^.*Account ending in\\s+(?<account>\\d+)$
ACTION_REGEX=^\\s*Action:\\s*\\s+(?<action>Purchase|Sale)\\s+$
DATE_FORMAT=MM/dd/yy
SYMBOL_REGEX=^\\s*Symbol:\\s*(?<symbol>[A-Z\\-]+)\\s*$
TRADE_REGEX=^\\s*Trade Date:\\s*(?<date>\\d{2}\\/\\d{2}\\/\\d{2})\\s*Settle Date:\\s*\\d{2}\\/\\d{2}\\/\\d{2}\\s*Quantity\\s*Price\\s*Principal\\s*Charge and/or Interest\\s*Total Amount\\s*(?<quantity>[\\d,]*.\\d*)\\s*\\$(?<price>[\\d,]*.\\d*)\\s+$
FROM=donotreply@mail.schwab.com
SUBJECT=Schwab eConfirms account ending in